version: '3'

services:
  authentication:
    build: .
    restart: always
    volumes:
      - ./:/authentication
    command: >
      sh -c "alembic upgrade head && uvicorn src.main:app --reload --host 0.0.0.0 --port 8001"
    ports:
      - '8001:8001'
      - '50051:50051'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    hostname: ${POSTGRES_HOST}
    image: postgres:alpine
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - PGPORT=${POSTGRES_PORT}

  redis:
    hostname: ${REDIS_HOST}
    image: redis
    ports:
      - "${REDIS_PORT}:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres


volumes:
  postgres_data:
