# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/permission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/permission.proto\x12\npermission\"!\n\x10\x43heckRoleRequest\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x11\x43heckRoleResponse\x12\x0c\n\x04role\x18\x01 \x01(\t\"#\n\x12\x43heckUserIDRequest\x12\r\n\x05token\x18\x01 \x01(\t\"&\n\x13\x43heckUserIDResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x32\xaa\x01\n\nPermission\x12J\n\tCheckRole\x12\x1c.permission.CheckRoleRequest\x1a\x1d.permission.CheckRoleResponse\"\x00\x12P\n\x0b\x43heckUserID\x12\x1e.permission.CheckUserIDRequest\x1a\x1f.permission.CheckUserIDResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.permission_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKROLEREQUEST']._serialized_start=39
  _globals['_CHECKROLEREQUEST']._serialized_end=72
  _globals['_CHECKROLERESPONSE']._serialized_start=74
  _globals['_CHECKROLERESPONSE']._serialized_end=107
  _globals['_CHECKUSERIDREQUEST']._serialized_start=109
  _globals['_CHECKUSERIDREQUEST']._serialized_end=144
  _globals['_CHECKUSERIDRESPONSE']._serialized_start=146
  _globals['_CHECKUSERIDRESPONSE']._serialized_end=184
  _globals['_PERMISSION']._serialized_start=187
  _globals['_PERMISSION']._serialized_end=357
# @@protoc_insertion_point(module_scope)
