"""empty message

Revision ID: e7a37fe4a387
Revises:
Create Date: 2023-10-24 07:37:46.036926

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e7a37fe4a387"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
