"""empty message

Revision ID: ad059f5190a5
Revises: 3c8e69885c69
Create Date: 2024-01-07 19:42:52.113649

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ad059f5190a5"
down_revision: Union[str, None] = "3c8e69885c69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification",
        sa.Column("code", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expiration", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_email_verification_created_at"), "email_verification", ["created_at"], unique=False)
    op.create_index(op.f("ix_email_verification_id"), "email_verification", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_verification_id"), table_name="email_verification")
    op.drop_index(op.f("ix_email_verification_created_at"), table_name="email_verification")
    op.drop_table("email_verification")
    # ### end Alembic commands ###
